name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release


jobs:
  build_and_test:
    name: '${{ matrix.os }}: build and test'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: setup vcpkg
      run: cd ~ && git clone https://github.com/microsoft/vcpkg.git && cd vcpkg && ./bootstrap-vcpkg.sh && export VCPKG_ROOT="~/vcpkg"
    
    - name: Configure CMake
      run: cd ${{github.workspace}} && cmake --preset M1-Mac-arm64-Release

    - name: Build
      run: cmake --build --preset mac-release --target Application